version: '3'
services:
  db:
    container_name: postgresTravelZone
    image: postgres
    environment:
      POSTGRES_USER: travelzone
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    ports:
      - "5433:5432"
    networks:
      - db
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local

networks:
  db:
    driver: bridge
